### ISSUE TITLE
How to mount cbica-cluster to CBIG-DL (or any linux desktop)

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#12]
<url>https://sbia-wiki.uphs.upenn.edu/wiki/index.php/Accessing_CBICA_networked_directories_from_your_Windows_or_Linux_desktop#Linux</url> has the description on how to do so. It was recently updated by Mark. There is no systemwide solution for all users. Every drive has to be individually mounted for each user following the steps below by each user and following the instruction in the link above as root.

Message sent to all lab members on 8/10/2018:
CBICA cluster directory mounting

As of now, the best solution to mount your personal and project directories to CBIG-DL is through mounting one-by-one by root which requires UPHS username and password. We haven’t found out a generic solution for all users yet since this computer is not linked to UPHS credential identification service. If you would like to have your cbica cluster directories (`/cbica/home/$user` and `/cbica/projects`) mounted on the file system, please do the following when you login and let me know that you are ready for mounting:

```bash
$ mkdir ~/cbica/home ~/cbica/projects
$ gedit ~/.cbica_mount_key  
username=${uphs_user_name}
password=${uphs_user_password}
$ chmod 700 ~/.cbica_mount_key  # very important. You don’t want anyone to read this. 
```

**Comment by gastouna** [comment]
Thanks! I followed these steps. What needs to be done now?

**Comment by hsieh42** [comment]
This is what I did for myself without saving the UPHS username and password into a text file.

```bash
$ sudo mount --verbose -t cifs //cbica-cifs/hsiehm ~/cbica/home -o username=hsiehm,domain=UPHS,vers=1.0,noserverino,uid=hsiehm,gid=hsiehm
```
It would then prompt me for a UPHS password.

Instead, if we should do something below to be more generic so that you can add for other users too after they define their .cbica_mount_key file. Note the first option `credentials`.
```bash
$ sudo mount --verbose -t cifs //cbica-cifs/${uphs_user_name} /home/${cbig_dl_username}/cbica/home -o credentials=/home/${cbig_dl_username}/.cbica_mount_key,domain=UPHS,vers=1.0,noserverino,uid=${uphs_user_name},gid=${uphs_user_name}
``` 
Having uid and gid in the options is to set the user and group for read/write permission properly.

**Comment by gastouna** [comment]
I was able to mount both home and the projects for myself. I used the command as suggested in SBIA wiki. For example:

$sudo mount --verbose -t cifs //cbica-cifs/projects ~/Documents/cbica/projects -o username=gastouna,domain=UPHS,vers=1.0,noserverino

I was not able to add it for other user though. I tried with Babak's account: uphs username = haghighb, username in CBIG-DL = bhaghighi

**Comment by hsieh42** [comment]
Check with @bhaghighi on his uphs password.

I was able to mount for Aimilia...
```bash
hsiehm@CBIG-DL:~$ sudo mount --verbose -t cifs //cbica-cifs/gastouna /home/gastouna/cbica/home/ -o credentials=/home/gastouna/Documents/cbica/.cbica_mount_key,domain=UPHS,vers=1.0,noserverino,uid=gastouna,gid=gastouna
mount.cifs kernel mount options: ip=170.212.169.36,unc=\\cbica-cifs\gastouna,vers=1.0,noserverino,uid=1001,gid=1001,user=gastouna,,domain=UPHS,pass=********
hsiehm@CBIG-DL:~$
```

**Comment by hsieh42** [comment]
To unmount:
`hsiehm@CBIG-DL:~$ sudo umount /home/gastouna/cbica/home/`

**Comment by gastouna** [comment]
I was finally able to mount for @bhaghighi. His password was one issue, but also needed correction in command:

```sudo mount --verbose -t cifs //cbica-cifs/${uphs_user_name} /home/${cbig_dl_username}/cbica/home -o credentials=/home/${cbig_dl_username}/.cbica_mount_key,domain=UPHS,vers=1.0,noserverino,uid=${cbig_dl_username},gid=${cbig_dl_username}```

**Comment by gastouna** [comment]
1. New name and IP address for the the network filesharing server.
	If you previously mounted network shares by IP address, please use the hostname:

		cubic-share.uphs.upenn.edu

	The former hostname (cbica-cifs) still works, but since the IP address has changed, you
	must unmount and then re-mount the network shares.


2. Change to path to home directory.
	The path to mount your home directory should use the literal word "home", and should no longer include your username.
	
	For example, the old path:
		\\cbica-cifs\$loginname
	must be updated to:
		\\cubic-share\home

3. Change in CIFS mount options for Linux users.

	There is a change required in the options to the "mount" command or in the option list in the /etc/fstab file. Remove the statement:

		vers=1.0

	The fileserver no longer supports (or requires) "version 1" of the SAMBA protocol. All modern CIFS clients support version 2, and version
	1 is terribly insecure. Many clients (Windows 10, for example) no longer have 'version 1' of the protocol.
