### ISSUE TITLE
Write-up I-SPY challenge

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#15]
How we did in the challenge and what we did. Methods and Results.

**Comment by hsieh42** [comment]
@eac-upenn did we ever write up something for the ispy challenge?

**Comment by eac-upenn** [comment]
I have my personal notes, I'll write something up.

**Comment by eac-upenn** [comment]
Done, I believe.
https://upenn.box.com/s/zu1m7l6ji65iw1gjrsvy7qhbyiyq85ko

Michael, let me know how to put them in a better part of Box, not within my personal directory tree, and I'll move them.

**Comment by eac-upenn** [comment]
Done.
https://upenn.box.com/s/zu1m7l6ji65iw1gjrsvy7qhbyiyq85ko
