### ISSUE TITLE
Create a github for dicom anonymization

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#19]
to host the python code /cbica/home/hsiehm/Scripts/remove_dicom_fields.py

**Comment by hsieh42** [comment]
See <url>https://github.com/hsieh42/dicom_manipulation/tree/master/anonymization</url>

**Comment by bhaghighi** [comment]
Got the warning: support skipfooter; you can avoid this warning by specifying engine='python'. 
Maybe adding a flag to help for engine="python"
