### ISSUE TITLE
Confirm project access to MayoRadiomics for Aimilia

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#2]
Check with her if she has access to /cbica/projects/MayoRadiomics. If not, she should have r+w access.

**Comment by gastouna** [comment]
> Check with her if she has access to /cbica/projects/MayoRadiomics. If not, she should have r+w access.

Corrected path: /cbica/projects/Mayo-Radiomics 
I belong to the mayoradiomics group which seems to have r+w access.

**Comment by hsieh42** [comment]
That only indicates that you have at least a read access. Please try to become project user with sudo. <url>https://sbia-wiki.uphs.upenn.edu/wiki/index.php/Research_Projects#Use_of_sudo_and_sudox_to_Become_a_Project_Owner</url>

**Comment by gastouna** [comment]
Thanks. I was able to become project user with sudo.

**Comment by hsieh42** [comment]
Great! I will open another thread so that we can talk about the data organization and processing. Thanks.
