### ISSUE TITLE
ctDNA workflow and analysis

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#20]
- Data collection
- DICOM sort and conversion to nifti
- How to read RECIST report from MINT
- itk-snap segmentation
- PyRadiomics
- Analyses using jupyter-notebook
- Survival analysis

**Comment by BardiaYou** [comment]
Michael, Could you please add a demo of what you have kindly shown in the meeting, how to get start with converting the process (in the DICOM anonymization)?
I already have "dicom_manipulation-master/anonymization", and want to continue using the toolbox.
Thank you

**Comment by hsieh42** [comment]
A note book is in the repo. Please see
<url>https://github.com/hsieh42/dicom_manipulation/blob/master/anonymization/dicom_manipulation_demo.ipynb</url>

**Comment by BardiaYou** [comment]
Thanks! Really helpful.

**Comment by BardiaYou** [comment]
I have a small problem running "run remove_dicom_fields.py -h", "show_dicomdir.py", I am receiving the syntax error. (Put my codes ([here](https://drive.google.com/open?id=1XLjrji0mK8yjCTNH3FGOs3VZdi3qw0UX)) and the files [(here)](https://drive.google.com/open?id=1_DwxSXxQK7F3WOuXfyXD9fBK-nRS60eV) ). Thank you for your help!

**Comment by hsieh42** [comment]
when you do `run some_code.py` you need to make sure that the code is either in the path or that you are in the directory where `some_code.py` is. To run codes in `dicom_manipulation-master/anonymization` you need to navigate into that directory. In cell 35, it shows that you are in `dicom_manipulation-master` therefore you can only run `read_dicom_header.py` or `sortdicom.py` but not codes in `dicom_manipulation-master/anonymization`.

**Comment by BardiaYou** [comment]
Thanks for the help!
I have given the address properly but
"
cd ".....\Codes\dicom_manipulation-master\anonymization"
run remove_dicom_fields.py -h
"
and again received this message: 
  File "<ipython-input-88-fd7e1ab5c95d>", line 1
    cd "......\Codes\dicom_manipulation-master\anonymization"
                                                                                 ^
SyntaxError: invalid syntax

**Comment by hsieh42** [comment]
Multiple dots in a relative path are invalid. A valid way to go up one level is two dots followed by a slash.

**Comment by BardiaYou** [comment]
Yes, I did not use it with dots. I used it as mentioned below:
cd "C:\Users\YousefiB\Documents\Codes\dicom_manipulation-master\anonymization"

but received an error:
File "<ipython-input-90-9d6802b1a180>", line 2
    run remove_dicom_fields.py -h
                          ^
SyntaxError: invalid syntax

**Comment by hsieh42** [comment]
> * Data collection
> * DICOM sort and conversion to nifti
> * How to read RECIST report from MINT
> * itk-snap segmentation
> * PyRadiomics
> * Analyses using jupyter-notebook
> * Survival analysis

Please find the analyses and slides in https://github.com/hsieh42/ctDNA. Closing the issue as we have discussed the whole project on 9/26/2018. Please create new issue should you encounter any.
