### ISSUE TITLE
Mayo-Radiomics weekly benchmark

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#21]
Tests are performed weekly on benchmark dataset and results are saved in `/cbica/projects/Mayo-Radiomics/Pipelines`. Benchmark dataset: `/cbica/projects/Mayo-Radiomics/Lists/MayoRadiomics_benchmark_img_20180807.list`.

```bash 
qsub -o /cbica/projects/Mayo-Radiomics/Pipelines/benchmark_${date}/logs \
         -l centos7 -t 1-$num_imgs \
         /cbica/projects/Mayo-Radiomics/Scripts/sendTexturePipeline_0.1.8.sh \
              /cbica/projects/Mayo-Radiomics/Lists/MayoRadiomics_benchmark_img_20180807.list \
              /cbica/projects/Mayo-Radiomics/pipelines/benchmark_$date/ \
              6.3 6.3 0
```

Document and Upload the analysis notebook so that @gastouna gets to know the process.

**Comment by hsieh42** [comment]
Update: disk quota exceeded so no more write access. All weekly tests suspended until further notice.

**Comment by hsieh42** [comment]
Closing the issue until we have more space.

**Comment by gastouna** [comment]
Benchmarking initiated today:

``qsub -o /cbica/projects/Mayo-Radiomics/Pipelines/benchmark_20181205/logs \
         -l centos7 -t 1-622 \
         /cbica/projects/Mayo-Radiomics/Scripts/sendTexturePipeline_0.1.8.sh \
              /cbica/projects/Mayo-Radiomics/Lists/MayoRadiomics_benchmark_img_20180807.list \
              /cbica/projects/Mayo-Radiomics/pipelines/benchmark_20181205/ \
              6.3 6.3 0
``
