### ISSUE TITLE
Run DICOM manipulation in jupyter-notebook with sample data

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#23]
and upload the notebooks.

Sample data: one study from ctDNA and one mammographic study.

**Comment by hsieh42** [comment]
See <url>https://github.com/hsieh42/dicom_manipulation/blob/master/anonymization/dicom_manipulation_demo.ipynb</url>

**Comment by bhaghighi** [comment]
Can we used Jupyter notebook in /cbica/CBIG/comp_space? I am getting this:

HTTP request sent; waiting for response.[I 16:43:05.369 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
localhost cookie: _xsrf=2|dff4ceff|0cb97770fa0cb8953b0e47b1495b489e|1537994585 Allow? (Y/N/Always/neVer)

**Comment by bhaghighi** [comment]
All of Script should necessarily be in comp_space of CBIG? For example, do we need to make a folder based on our name if any of us would like to tweak or modify the codes a little bit?  
Thanks,

**Comment by hsieh42** [comment]
> Can we used Jupyter notebook in /cbica/CBIG/comp_space? I am getting this:
> 
> HTTP request sent; waiting for response.[I 16:43:05.369 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
> localhost cookie: _xsrf=2|dff4ceff|0cb97770fa0cb8953b0e47b1495b489e|1537994585 Allow? (Y/N/Always/neVer)

Did you try any option? Did it work? jupyter-notebook on the cluster can be sometimes funny. You should report system issue to elog.

**Comment by hsieh42** [comment]
> All of Script should necessarily be in comp_space of CBIG? For example, do we need to make a folder based on our name if any of us would like to tweak or modify the codes a little bit?
> Thanks,

@bhaghighi You are welcome to clone a copy of the code in the repo to any location you prefer. Always point the cfg file to the one in `/cbica/comp_space/CBIG`. If you wish to tweak the code, you can do a pull request.
