### ISSUE TITLE
Quantra pushing code and account manangement

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#4]
Codes in <url>https://sbia-svn/projects/CBIG/quantraPushing/</url>.
Hologic remote server information: 
IP: <url>10.170.3.188</url>
Domain name: CENOVA
Account name: siteadmin
Password: ask Michael for a note.

Note: Quantra only works with raw mammograms of MLO and CC views. It will reject all other images.

**Comment by hsieh42** [comment]
@gastouna Please try to run the code with some raw mammograms you have handy. We can then log on to the CENOVA server to see the results. Also let me know if the code is self-explanatory.

**Comment by gastouna** [comment]
I pushed 2 cases. Are the following warnings/errors expected?
Let's check the results (if any) together when you have a minute.

----
Requesting Association 
Association Accepted (Max Send PDV: 64222) 
-------------------------- 
Sending file: C:\Users\gastouna\Documents\Aimilias research - Complementary files\quantraPushing\TESTimages\75289376\75289376_L_MLO_1.dcm 
Transfer: JPEGLossless:Non-hierarchical-1stOrderPrediction -> LittleEndianExplicit 
Store SCU RQ: MsgID 1, (DXm) 
**XMIT:DIMSE Warning: (STORESCU,R2MAMMOCAD5): sendMessage: unable to convert dataset** 
from 'JPEG Lossless, Non-hierarchical, 1st Order Prediction' transfer syntax to 'LittleEndianExplicit'. 
 
**storescu: Store Failed, file: C:\Users\gastouna\Documents\Aimilias research - Complementary files\quantraPushing\TESTimages\75289376\75289376_L_MLO_1.dcm:** 
0006:020e DIMSE Failed to send message 
storescu: SCU Failed: 
0006:020e DIMSE Failed to send message 
Aborting Association 
         Sending of dicom C:\Users\gastouna\Documents\Aimilias research - Complementary files\quantraPushing\TESTimages\75289376\75289376_L_MLO_1.dcm Complete!

**Comment by gastouna** [comment]
A couple more questions:

- I used the "pushCases2Quantra". Should I be using the "ushDicom2QuantraByCase" instead? The Readme file is confusing.
- How can we run Quantra for large datasets on the cluster? Have you been using an executable?

**Comment by hsieh42** [comment]
`pushCases2Quantra.m` should be used as the entry point. Sorry for the confusion created by the wrong indentation in Readme.txt. I have updated the codes and Readme.txt on the svn. Please update.

To your second point, though running the pushing codes on the cluster should be feasible as storescu binary is also available on the cluster but I have never attempted to do so. I typically run it from my desktop with the full path to the data wherever they are, an external HD or cbica cluster. Often times I have to push from a hard drive and that's why I do it from my desktop with the HD plugged in. Fo data on the cluster, you could map the cbica-cluster directory on your PC [this way](https://sbia-wiki.uphs.upenn.edu/wiki/index.php/Accessing_CBICA_networked_directories_from_your_Windows_or_Linux_desktop#Windows).

**Comment by hsieh42** [comment]
> Requesting Association
> Association Accepted (Max Send PDV: 64222)
> Sending file: C:\Users\gastouna\Documents\Aimilias research - Complementary files\quantraPushing\TESTimages\75289376\75289376_L_MLO_1.dcm
> Transfer: JPEGLossless:Non-hierarchical-1stOrderPrediction -> LittleEndianExplicit

It's complaining that the DICOM image is JPEGLossless compressed, instead of uncompressed format, LittleEndianExplicit.

See [this](https://www.dicomlibrary.com/dicom/transfer-syntax/) for more information about the TransferSyntax UID. Only the first 4 on top are the uncompressed format, the rest is somehow manipulated.

**Comment by hsieh42** [comment]
Example code:
```matlab
exedir='C:\Users\hsiehm\Documents\SBIA\Breasts\Quantra_Pushing-SVN';
addpath(exedir);
parentdir='V:\Prospr\Data\BreastAnatomy\Mayo\20180427'; 
% parentdir contains sub-directories of dicom files
odir='C:\Users\hsiehm\Documents\SBIA\Breasts\Aimilia\Results\Quantra-2.2.1';
% to save a log file to the odir using diary
log = fullfile(odir, ['pushCases2Quantra_' datestr(now, 'yyyymmdd') '.txt']); 
diary(log);
pushCases2Quantra(parentdir, exedir);
diary off;
```
